import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "secondary-container": "#0566d9",
        "on-error": "#690005",
        "on-primary-container": "#00424f",
        "on-primary": "#003640",
        "primary-fixed": "#acedff",
        "surface-bright": "#31394d",
        "secondary-fixed": "#d8e2ff",
        "inverse-on-surface": "#283044",
        "surface-container-high": "#222a3d",
        "inverse-surface": "#dae2fd",
        "tertiary-fixed": "#6ffbbe",
        "on-tertiary": "#003824",
        background: "#0b1326",
        "surface-container-low": "#131b2e",
        "on-surface": "#dae2fd",
        error: "#ffb4ab",
        secondary: "#adc6ff",
        "error-container": "#93000a",
        "primary-container": "#06b6d4",
        "secondary-fixed-dim": "#adc6ff",
        "outline-variant": "#3d494c",
        "on-error-container": "#ffdad6",
        "surface-container-lowest": "#060e20",
        "on-tertiary-fixed": "#002113",
        "on-primary-fixed-variant": "#004e5c",
        "inverse-primary": "#00687a",
        "on-secondary-container": "#e6ecff",
        "surface-tint": "#4cd7f6",
        tertiary: "#4edea3",
        "primary-fixed-dim": "#4cd7f6",
        "on-tertiary-container": "#00452e",
        outline: "#869397",
        "surface-container": "#171f33",
        "on-secondary": "#002e6a",
        "surface-container-highest": "#2d3449",
        "tertiary-container": "#1bbd85",
        "tertiary-fixed-dim": "#4edea3",
        "on-surface-variant": "#bcc9cd",
        "on-tertiary-fixed-variant": "#005236",
        primary: "#4cd7f6",
        "surface-dim": "#0b1326",
        "surface-variant": "#2d3449",
        "on-primary-fixed": "#001f26",
        "on-background": "#dae2fd",
        "on-secondary-fixed": "#001a42",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "system-ui", "sans-serif"],
        display: ["var(--font-sora)", "system-ui", "sans-serif"],
      },
      fontSize: {
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "16px", fontWeight: "600" }],
        "display-hero-mobile": ["40px", { lineHeight: "48px", fontWeight: "800" }],
        "headline-lg": ["48px", { lineHeight: "56px", fontWeight: "700" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-hero": ["64px", { lineHeight: "72px", fontWeight: "800" }],
        "title-md": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "headline-sm": ["22px", { lineHeight: "30px", fontWeight: "600" }],
        "headline-md": ["30px", { lineHeight: "38px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
